spring:
  application:
    name: souli-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:25}
    username: ${MAIL_USERNAME:no-reply@souli.local}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:false}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS:false}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml

cors:
  allowed-origins:
    - ${CORS_ALLOWED_ORIGIN:http://localhost:4200}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600
  refresh-token-expiration: 604800
